Repository vinitshahdeo/Water-Monitoring-System, pull requests merged in 2020-05, with the labels that each got.

#184 created route to add a new tank Issue #160
  api/models/Reading.js
  api/routes/tankroutes.js
Labels: gssoc20, medium

#261 Synch up README.md from 'master' branch
  README.md
  _config.yml
Labels: bug, documentation, enhancement

#273 Added New mentor
  README.md
Labels: easy, gssoc20

#274 Added a new Mentor
  README.md
Labels: easy, gssoc20

#263 Feature/backend node
  api/.dockerignore
  api/Dockerfile
  api/README.md
Labels: gssoc20, hard

#278 Making Readme File more Readable
  .github/config.yml
  README.md
  assets/rgsoc2020.png
Labels: easy, gssoc20

#287 Added tagline!
  src/home.html
  src/water-drop.png
Labels: easy, gssoc20

#182 Feature/inline external to bootstrap
  .gitignore
  netlify.toml
  package-lock.json
  package.json
  react-frontend/.gitignore
  react-frontend/README.md
  react-frontend/package-lock.json
  react-frontend/package.json
  react-frontend/public/favicon.ico
  react-frontend/public/index.html
  react-frontend/public/logo192.png
  react-frontend/public/logo512.png
  react-frontend/public/manifest.json
  react-frontend/public/robots.txt
  react-frontend/public/worker.js
  react-frontend/src/App.css
  react-frontend/src/App.js
  react-frontend/src/actions/tankActions.js
  react-frontend/src/actions/types.js
  react-frontend/src/components/Sticker.js
  react-frontend/src/components/Tank.js
  react-frontend/src/index.css
  react-frontend/src/index.js
  react-frontend/src/logo.svg
  react-frontend/src/pages/Home.js
  react-frontend/src/reducers/index.js
  react-frontend/src/reducers/tankReducer.js
  react-frontend/src/serviceWorker.js
  react-frontend/src/setupTests.js
  react-frontend/src/store/store.js
  react-frontend/yarn.lock
  screenshots/Instance #1/LandingPageDesign.png
  screenshots/Instance #3/1.1.PNG
  screenshots/Instance #3/1.1.png
  screenshots/Instance #3/1.2.PNG
  screenshots/Instance #3/1.3.PNG
  screenshots/Instance #3/2.1.PNG
  screenshots/Instance #8/Screenshot (01).png
  screenshots/Instance #8/Screenshot (02).png
  screenshots/Instance #8/Screenshot (03).png
  screenshots/Instance #8/Screenshot (04).png
  screenshots/Instance #8/Screenshot (05).png
  screenshots/Instance #8/Screenshot (06).png
  screenshots/Instance #8/landing_page.xd
  screenshots/Instance No. #9/Design.xd
  screenshots/Instance No. #9/screenshot1.jpg
  screenshots/instance#4/design.jpg
  screenshots/instance#4/design.psd
  screenshots/instance#7/WMSDesign.png
  screenshots/instance#7/WaterMonitoringSystem.xd
  src/1.PNG
  src/demo.html
  src/home.html
Labels: gssoc20, medium

#289 Here, I have added new mentor details
  README.md
  git-workflow.svg
Labels: easy, gssoc20

#300 adding the jumbotron
  src/home.html
Labels: gssoc20, medium

#302 Adding the Purpose section in the HomePage
  assets/alert.png
  assets/cost.jpg
  assets/phone.jpg
  assets/time.jpg
  assets/water.jpg
  assets/water1.jpg
  src/home.html
Labels: easy, gssoc20

#303 Added Open Source section
  assets/img1.jpeg
  assets/img2.jpeg
  src/home.html
Labels: gssoc20, medium

#258 FIX: Removing typos in FAQ section
  .github/config.yml
  README.md
  git-workflow.svg
Labels: gssoc20

#305 Adding the responsive navbar
  assets/logo.jpg
  src/home.html
Labels: easy, gssoc20
