Repository vinitshahdeo/Water-Monitoring-System, pull requests merged in 2020-03, with the labels that each got.

#88 Added link to Open Source Programs
  README.md
Labels: gssoc20

#94 resource added for Node.js -Issue #32
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
Labels: easy, gssoc20

#96 Edited the link to GirlScript Foundation
  README.md
Labels: easy, gssoc20

#95 Update README.md
  README.md
Labels: easy, gssoc20

#113 Updated name in package.json
  react-frontend/package.json
Labels: easy, gssoc20

#86 Making PWA
  react-frontend/package-lock.json
  react-frontend/public/index.html
  react-frontend/public/manifest.json
  react-frontend/public/worker.js
  react-frontend/src/index.js
  react-frontend/src/pages/Home.js
Labels: gssoc20, medium

#78 Updated LICENSE.MD
  LICENSE
Labels: easy, gssoc20

#110 updated name in api/package.json file
  README.md
  api/package.json
Labels: easy, gssoc20

#67 added netlify.toml config file to feature/frontend
  netlify.toml
Labels: gssoc20

#85 Add badges
  README.md
Labels: easy, gssoc20

#139 Feature/meta tags
  src/demo.html
  src/home.html
Labels: gssoc20, medium

#151 Add Footer
  src/home.html
Labels: easy, gssoc20

#153 Adding Footer. Fixes #56
  src/home.html
Labels: easy, gssoc20

#178 Add slack badge
  README.md
Labels: easy, gssoc20

#72 Added the instructions to setup working environment
  src/demo.html
  src/home.html
Labels: easy, gssoc20

#128 Added animation to Water Tank Flow
  src/home.html
Labels: easy, gssoc20

#210 Modification done in Readme
  README.md
Labels: easy, gssoc20

#212 Updated Footer
  src/home.html
Labels: easy, gssoc20

#183 Implementation of phone auth on node.js backend
  api/package-lock.json
  api/package.json
  api/routes/auth.js
  api/server.js
Labels: gssoc20, medium

#213 Landing Page Design
  screenshots/Instance #1/LandingPageDesign.png
Labels: gssoc20, medium

#206 New Landing Page Design
  screenshots/Instance No. #9/Design.xd
  screenshots/Instance No. #9/screenshot1.jpg
Labels: design, gssoc20, hard
