Repository vinitshahdeo/Water-Monitoring-System, pull requests merged in 2020-04, with the labels that each got.

#223 Fixed Footer
  src/home.html
Labels: easy, gssoc20

#220 Feature/documentation
  Resources/GSSOC 20.png
Labels: easy, gssoc20

#136 Added Authorization Token
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  Resources/infographic.png
  assets/rgsoc2020.png
  assets/vinit-shahdeo.jpg
  docs/Web-Based Water Monitoring System.pdf
  src/demo.html
  src/home.html
  src/lib/createWaterBall-jquery.js
  water_monitoring_system/.vscode/settings.json
  water_monitoring_system/config/settings/base.py
  water_monitoring_system/manage.py
  water_monitoring_system/utility/install_os_dependencies.sh
  water_monitoring_system/utility/install_python_dependencies.sh
  water_monitoring_system/water_monitoring_system/templates/users/invalid_token.html
  water_monitoring_system/water_monitoring_system/users/models.py
  water_monitoring_system/water_monitoring_system/users/views.py
Labels: backend, gssoc20, hard

#227 Landing Page Design in AdobeXD (Instance #7)
  screenshots/instance#7/WMSDesign.png
  screenshots/instance#7/WaterMonitoringSystem.xd
Labels: gssoc20, medium

#181 Added Tank Details for Reading route
  api/models/Reading.js
  api/routes/readingRoutes.js
  package-lock.json
Labels: gssoc20, medium

#237 API endpoints for hardware models
  water_monitoring_system/water_monitoring_system/hardware/api/serializers.py
  water_monitoring_system/water_monitoring_system/hardware/api/views.py
  water_monitoring_system/water_monitoring_system/hardware/urls.py
Labels: backend, gssoc20, medium

#239 Develop login and signup page
  src/loginpage.html
  src/signuppage.html
Labels: gssoc20, medium
